language: ruby
rvm:
  - 1.9.3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - exec rackup &
  - sleep 6
script: phantomjs qunit/run-qunit.js "http://localhost:9292/index.html?package=all" && "RAILS_ENV=test bundle exec rake test:ci --trace" && "rake jasmine:headless"